DocSpin2/Models/ACLViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DocSpin2.Models
{
	[NotMapped]
	public class ACLItemViewModel
	{
		public int model_id;
		public string user_id, user_name;
		public AccessControlSetting acs;
	}

	[NotMapped]
	public class ACLViewModel
	{
		public enum Type
		{
			Repository,
			Document
		}
		public Type src_type;
		public int src_type_id;
		public string src_type_name;

		public IEnumerable<ACLItemViewModel> elements;
	}

	[NotMapped]
	public class ACLCreateModel
	{
		public int object_id { get; set; }
		public string object_type { get; set; }
		public string user_id { get; set; }
		public AccessControlSetting ACS { get; set; }
	}

	[NotMapped]
	public class ACLDeleteModel : ACLCreateModel
	{
		public string object_name;
		public string repo_name = "";
		public string user_name;
	}
}

DocSpin2/Controllers/ACLsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DocSpin2.Models;
using DocSpin2.Util;

namespace DocSpin2.Controllers
{
	[Authorize]
    public class ACLsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ACLs
        public ActionResult Index()
        {
            return View();
        }

		// ACList for specific repo/doc
        // GET: ACLs/Details/5?type=Repository|Document
        public ActionResult Details(int? id, string type)
        {
			if (id == null || !(type == "Repository" || type == "Document"))
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			if (type == "Repository")
			{
				var ret = CheckRepositorySupervisor((int)id);
				if (ret != null)
					return ret;

				var repo = db.RepositorySet.FirstOrDefault(r => r.Id == id);

				var acl = from a in db.RepositoryACLSet.Include(r => r.User)
						  where a.RepositoryId == id
						  select new ACLItemViewModel
						  {
							  model_id = a.Id,
							  user_id = a.UserId,
							  user_name = a.User.FullName,
							  acs = a.ACS
						  };

				return View(new ACLViewModel
					{
						src_type = ACLViewModel.Type.Repository,
						src_type_id = (int)id,
						src_type_name = repo.Name,
						elements = acl.ToList()
					});
			}	
			else
			{
				var ret = CheckDocumentSupervisor((int)id);
				if (ret != null)
					return ret;

				var doc = db.DocumentSet.Where(d => d.Id == id)
					.Include(d => d.Repository).FirstOrDefault();
				
				var acl = from a in db.DocumentACLSet.Include(r => r.User)
						  where a.DocumentId == id
						  select new ACLItemViewModel
						  {
							  model_id = a.Id,
							  user_id = a.UserId,
							  user_name = a.User.FullName,
							  acs = a.ACS
						  };

				return View(new ACLViewModel
					{
						src_type = ACLViewModel.Type.Document,
						src_type_id = (int)id,
						src_type_name = doc.Repository.Name,
						elements = acl.ToList()
					});
			}
        }

		// GET: ACLs/Create/5?type=Repository|Document
        public ActionResult Create(int? id, string type)
        {
			if (id == null || !(type == "Repository" || type == "Document"))
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			var ret = CheckSupervisor(type, (int)id);
			if (ret != null)
				return ret;

			ViewData["UsersList"] = 
				new SelectList(ApplicationUser.GetList(), "Id", "FullName");

			return View(new ACLCreateModel
			{
				object_id = id.Value,
				object_type = type,
				ACS = AccessControlSetting.None
			});
        }

        // POST: ACLs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "object_id,object_type,user_id,ACS")] ACLCreateModel acl)
        {
			if (!(acl.object_type == "Repository" || acl.object_type == "Document"))
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			var ret = CheckSupervisor(acl.object_type, acl.object_id);
			if (ret != null)
				return ret;

			if (ModelState.IsValid)
            {
				if (acl.object_type == "Repository")
					db.RepositoryACLSet.Add(new RepositoryACL 
					{
						RepositoryId = acl.object_id,
 						ACS = acl.ACS,
						UserId = acl.user_id
					});
				else
					db.DocumentACLSet.Add(new DocumentACL
					{
						DocumentId = acl.object_id,
						ACS = acl.ACS,
						UserId = acl.user_id
					}); 
				db.SaveChanges();
				return RedirectToAction("Details", new { id = acl.object_id, type = acl.object_type });
            }

			ViewData["UsersList"] =
				new SelectList(ApplicationUser.GetList(), "Id", "FullName");
			
			return View(acl);
        }

        // GET: ACLs/Delete/5
        public ActionResult Delete(int? id, string type)
        {
			if (id == null || !(type == "Repository" || type == "Document"))
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			var ret = CheckSupervisor(type, (int)id);
			if (ret != null)
				return ret;

			ACLDeleteModel acl;
			if (type == "Document")
			{
				var fetch = db.DocumentACLSet.Where(d => d.Id == id)
					.Include(d => d.Document)
					.Include(d => d.Document.Repository)
					.Include(d => d.User).FirstOrDefault();
				acl = new ACLDeleteModel
				{
					object_id = fetch.Id,
					object_name = fetch.Document.Name,
					object_type = "Document",
					repo_name = fetch.Document.Repository.Name,
					ACS = fetch.ACS,
					user_name = fetch.User.FullName
				};
			} 
			else
			{
				var fetch = db.RepositoryACLSet.Where(r => r.Id == id)
					.Include(r => r.Repository)
					.Include(r => r.User).FirstOrDefault();
				acl = new ACLDeleteModel
				{
					object_id = fetch.Id,
					object_name = fetch.Repository.Name,
					object_type = "Repository",
					ACS = fetch.ACS,
					user_name = fetch.User.FullName
				};
			}
			
            return View(acl);
        }

        // POST: ACLs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed([Bind(Include = "object_id,object_type")] ACLDeleteModel acl)
        {
			if (!(acl.object_type == "Repository" || acl.object_type == "Document"))
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			var ret = CheckSupervisor(acl.object_type, acl.object_id);
			if (ret != null)
				return ret;

			if (acl.object_type == "Repository")
			{
				var fetch = db.RepositoryACLSet.FirstOrDefault(r => r.Id == acl.object_id);
				db.RepositoryACLSet.Remove(fetch);
			}
			else
			{
				var fetch = db.DocumentACLSet.FirstOrDefault(d => d.Id == acl.object_id);
				db.DocumentACLSet.Remove(fetch);
			}

			db.SaveChanges();
			return RedirectToAction("Details", new { id = acl.object_id, type = acl.object_type });
		}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
		}

		#region helpers

		private ActionResult CheckSupervisor(string type, int id)
		{
			if (type == "Repository")
			{
				var ret = CheckRepositorySupervisor(id);
				if (ret != null)
					return ret;
			}
			else
			{
				var ret = CheckDocumentSupervisor(id);
				if (ret != null)
					return ret;
			}
			return null;
		}

		private ActionResult CheckRepositorySupervisor(int id)
		{
			var repo = db.RepositorySet.FirstOrDefault(r => r.Id == id);
			if (repo == null)
				return HttpNotFound();
			if (!repo.IsSupervisor)
				return View("AuthError", new ObjectAuthError(ObjectAuthErrorReason.RepositoryActionDenied,
					"You must be a supervisor to add ACL on repo id=" + id));
			return null;
		}

		private ActionResult CheckDocumentSupervisor(int id)
		{
			var doc = db.DocumentSet.Where(d => d.Id == id)
				.Include(d => d.Repository).FirstOrDefault();
			if (doc == null)
				return HttpNotFound();
			//TODO: maybe extend to doc's acs Supervisor prop
			if (!doc.Repository.IsSupervisor)
				return View("AuthError", new ObjectAuthError(ObjectAuthErrorReason.DocumentActionDenied,
					"You must be a repository supervisor to add ACL on document id=" + id + ", repo id=" + doc.RepositoryId));
			return null;
		}

		#endregion
	}
}

DocSpin2/Views/ACLs/Create.cshtml
@model DocSpin2.Models.ACLCreateModel
@using DocSpin2.Models

@{
	string singular = Model.object_type;
	string plural = (singular == "Document" ? "Documents" : "Repositories");
	ViewBag.Title = "ACL for " + singular;
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Repository</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("User", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
				@Html.DropDownListFor(model => model.user_id, ViewData["UsersList"] as SelectList, new { @class = "form-control" })
                @*@Html.EditorFor(model => model.user_id, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
            </div>
        </div>

		@Html.Partial("_ACSFieldPartial", Model == null ? new AccessControlSetting() : Model.ACS, new ViewDataDictionary { {"with_none" , true} })

		@Html.HiddenFor(model => model.object_type)
		@Html.HiddenFor(model => model.object_id)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = Model.object_id, type = Model.object_type })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DocSpin2/Views/ACLs/Delete.cshtml
@model DocSpin2.Models.ACLDeleteModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>@Model.object_type ACL</h4>
    <hr />
    <dl class="dl-horizontal">
	@if (Model.object_type == "Repository")
	{
		<dt>
			Repository
		</dt>
		<dd>
			@Html.DisplayFor(model => model.object_name)
		</dd>
	}
	else
	{
		<dt>
			Repository
		</dt>
		<dd>
			@Html.DisplayFor(model => model.repo_name)
		</dd>

		<dt>
			Document
		</dt>
		<dd>
			@Html.DisplayFor(model => model.object_name)
		</dd>
	}

		<dt>
			User
		</dt>
		<dd>
			@Html.DisplayFor(model => model.user_name)
		</dd>

        <dt>
            ACS
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ACS)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

		@Html.HiddenFor(m => m.object_id)
		@Html.HiddenFor(m => m.object_type)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Details", new { id = Model.object_id, type = Model.object_type })
        </div>
    }
</div>

DocSpin2/Views/ACLs/Details.cshtml
@model DocSpin2.Models.ACLViewModel

@{
	string singular = (Model.src_type == DocSpin2.Models.ACLViewModel.Type.Document ? "Document" : "Repository");
	string plural = (Model.src_type == DocSpin2.Models.ACLViewModel.Type.Document ? "Documents" : "Repositories");
	ViewBag.Title = "ACL for " + singular + " " + Model.src_type_name;
}

<h2>Details</h2>

<div>
    <h4>@singular ACL</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
           @singular name
        </dt>
        <dd>
            @Html.DisplayFor(model => model.src_type_name)
        </dd>
    </dl>
</div>
<p>
	@Html.ActionLink("Add new entry", "Create", new { id = Model.src_type_id, type = singular })
    <br /> 
	@Html.ActionLink("Back to " + singular, "Index", plural, new { id = Model.src_type_id }) 
</p>

<table class="table">
    <tr>
        <th>
            User name
        </th>
        <th>
            ACS
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.elements)
    {
        <tr>
            <td>
                @Html.DisplayFor(i => item.user_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.acs)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", "ACLs", new { id = item.model_id, type = singular })
            </td>
        </tr>
    }
</table>

DocSpin2/Views/ACLs/Index.cshtml
@model IEnumerable<DocSpin2.Models.Repository>

@{
    ViewBag.Title = "Repositories";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="row">
	@foreach (var itm in Model)
	{
		using (Html.BeginForm("Details", "Repositories", new { id = itm.Id }, FormMethod.Post, new { @class = "col-md-4"}))
		{
			string attrib = itm.IsSupervisor ? " btn-success" : (itm.IsReadOnly ? "" : " btn-info");
			
			<button type="submit" class="btn btn-lg btn-block@(attrib)">@Html.DisplayFor(d => itm.Name)</button>
		}
	}
</div>